version: "3.9"

services:

  api:
    build: .
    container_name: resume_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - ./chroma_db:/app/chroma_db

  db:
    image: postgres:16
    container_name: resume_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resume_db
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: